var actionProperties = {
    run_workflow_now: {
        id: "block47",
        name: "run_workflow_now",
    },
    end_workflow: {
        id: "block48",
        name: "end_workflow",
    },
    product_not_viewed: {
        id: "block1",
        name: "product_not_viewed",
        product_id: "",
        days: "",
    },
    any_product_not_viewed: {
        id: "block2",
        name: "any_product_not_viewed",
        days: "",
    },
    product_purchased: {
        id: "block3",
        name: "product_purchased",
        product_id: "",
        //amount: "",
        perc_amount: "",
        days: "",
    },
    any_product_purchased: {
        id: "block4",
        name: "any_product_purchased",
        perc_amount: "",
        days: "",
    },
    product_added_to_cart: {
        id: "block12",
        name: "product_added_to_cart",
        product_id: "",
    },
    13: {
        id: "block13",
        name: "product_added_to_cart2",
        my_param: "",
        my_param_2: "",
    },
    product_not_purchased: {
        id: "block14",
        name: "product_not_purchased",
        product_id: "",
        days: "",
    },
    any_product_not_purchased: {
        id: "block15",
        name: "any_product_not_purchased",
        days: "",
    },
    x_purchases_made: {
        id: "block16",
        name: "x_purchases_made",
        amount: "",
        days: "",
    },
    coupon_used: {
        id: "block17",
        name: "coupon_used",
        coupon_id: "",
        amount: "",
        days: "",
    },
    any_coupon_used: {
        id: "block18",
        name: "any_coupon_used",
        amount: "",
        days: "",
    },
    product_viewed: {
        id: "block19",
        name: "product_viewed",
        product_id: "",
        perc_amount: "",
        days: "",
    },
    any_product_viewed: {
        id: "block20",
        name: "any_product_viewed",
        perc_amount: "",
        days: "",
    },
    product_cat_viewed: {
        id: "block21",
        name: "product_cat_viewed",
        cat_id: "",
        perc_amount: "",
        days: "",
    },
    any_product_cat_viewed: {
        id: "block49",
        name: "any_product_cat_viewed",
        perc_amount: "",
        days: "",
    },
    any_rec_product_clicked: {
        id: "block22",
        name: "any_rec_product_clicked",
        amount: "",
        days: "",
    },
    upsell_clicked: {
        id: "block23",
        name: "upsell_clicked",
        amount: "",
        days: "",
    },
    product_older_than: {
        id: "block24",
        name: "product_older_than",
        product_id: "",
        days: "",
    },
    any_product_older_than: {
        id: "block25",
        name: "any_product_older_than",
        days: "",
    },
    wait_x_days: {
        id: "block26",
        name: "wait_x_days",
        days: "",
    },
    x_new_users: {
        id: "block27",
        name: "x_new_users",
        amount: "",
        days: "",
    },
    calculate_category: {
        id: "block28",
        name: "calculate_category",
        datapoint: "",
        days: "",
    },
    put_product_on_sale: {
        id: "block29",
        name: "put_product_on_sale",
        product_id: "",
        percentage: "",
    },
    take_product_off_sale: {
        id: "block30",
        name: "take_product_off_sale",
        product_id: "",
    },
    put_all_products_on_sale: {
        id: "block31",
        name: "put_all_products_on_sale",
        percentage: "",
    },
    take_all_products_off_sale: {
        id: "block32",
        name: "take_all_products_off_sale",
    },
    put_category_on_sale: {
        id: "block33",
        name: "put_category_on_sale",
        cat_id: "",
        percentage: "",
    },
    take_category_off_sale: {
        id: "block34",
        name: "take_category_off_sale",
        cat_id: "",
    },
    change_default_price: {
        id: "block35",
        name: "change_default_price",
        product_id: "",
        price: "",
    },
    change_upsell_product: {
        id: "block36",
        name: "change_upsell_product",
        product_id: "",
    },
    enable_disable_upsell: {
        id: "block37",
        name: "enable_disable_upsell",
        enable_disable: "",
    },
    product_to_recommended: {
        id: "block38",
        name: "product_to_recommended",
        product_id: "",
    },
    product_off_recommended: {
        id: "block39",
        name: "product_off_recommended",
        product_id: "",
    },
    display_product_everywhere: {
        id: "block40",
        name: "display_product_everywhere",
        product_id: "",
    },
    make_product_featured: {
        id: "block41",
        name: "make_product_featured",
        product_id: "",
    },
    make_product_not_featured: {
        id: "block42",
        name: "make_product_not_featured",
        product_id: "",
    },
    change_product_status: {
        id: "block43",
        name: "change_product_status",
        product_id: "",
        product_status: "",
    },
    send_admin_alert: {
        id: "block44",
        name: "send_admin_alert",
        email: "",
        message: "",
    },
    every_x_days: {
        id: "block45",
        name: "every_x_days",
        days: "",
        start_date: "",
    },
    on_set_date: {
        id: "block46",
        name: "on_set_date",
        start_date: "",
    },
    add_remove_tag: {
        id: "block47",
        name: "add_remove_tag",
        add_remove: "",
        product_tag: "",
        product_id: "",
    },
    change_topbar_text: {
        id: "block48",
        name: "change_topbar_text",
        message: "",
    },
    enable_disable_topbar: {
        id: "block48",
        name: "enable_disable_topbar",
        enable_disable: "",
    },
    change_product_badge: {
        id: "block49",
        name: "change_product_badge",
        product_id: "",
        product_badge: "",
    },
    calculate_product: {
        id: "block50",
        name: "calculate_product",
        product_filters: "",
        days: "",
    },
    change_product_display: {
        id: "block50",
        name: "change_product_display",
        display_id: "",
        product_id: "",
    },
    product_stock: {
        id: "block51",
        name: "product_stock",
        product_id: "",
        above_below: "",
        amount: "",
    },
    any_product_stock: {
        id: "block52",
        name: "any_product_stock",
        above_below: "",
        amount: "",
    },
    show_hide_product: {
        id: "block53",
        name: "show_hide_product",
        product_id: "",
        show_hide: "",
    },
    // ... other actions
};