// Array holding unique 'value' strings for actions
const actionStrings = [
    "put_product_on_sale",
    "take_product_off_sale",
    "put_all_products_on_sale",
    "take_all_products_off_sale",
    "put_category_on_sale",
    "take_category_off_sale",
    "change_default_price",
    "change_upsell_product",
    "enable_disable_upsell",
    "product_to_recommended",
    "product_off_recommended",
    "display_product_everywhere",
    "make_product_featured",
    "make_product_not_featured",
    "change_product_status",
    "send_admin_alert",
    "add_remove_tag",
    "change_topbar_text",
    "enable_disable_topbar",
    "change_product_badge",
    "change_product_display", 
    "show_hide_product", 
];

// Array holding unique 'value' strings for events
const eventStrings = [
    "calculate_category",
    "calculate_product",
    "run_workflow_now",
    "end_workflow",
    "product_not_viewed",
    "any_product_not_viewed",
    "product_purchased",
    "any_product_purchased",
    "product_not_purchased",
    "any_product_not_purchased",
    "x_purchases_made",
    "coupon_used",
    "any_coupon_used",
    "product_viewed",
    "any_product_viewed",
    "product_cat_viewed",
    "any_product_cat_viewed",
    "any_rec_product_clicked",
    "upsell_clicked",
    "product_older_than",
    "any_product_older_than",
    "wait_x_days",
    "x_new_users",
    "every_x_days",
    "on_set_date",
    "product_stock",
    "any_product_stock"
];